/**
 * Project Timeline — Multi-epic data layer.
 *
 * ⚠️  AUTO-GENERATED by Flow Orbit (scripts/nf-product-manager.ts)
 *     Run `pnpm pm` to refresh. Do not edit manually.
 *     Last sync: 2026-04-23T17:18:27.164Z
 */

export type EntryStatus = 'done' | 'in-progress' | 'backlog' | 'cancelled';
export type EntryType = 'task' | 'release' | 'milestone';

export interface TimelineEntry {
  id: string;
  jiraKey?: string;
  type: EntryType;
  title: string;
  description?: string;
  status: EntryStatus;
  date?: string;
  jiraUrl?: string;
  tags?: string[];
  priority?: 'high' | 'medium' | 'low';
}

export interface EpicDefinition {
  key: string;
  title: string;
  shortTitle: string;
  description: string;
  url: string;
  status: 'done' | 'in-progress' | 'backlog';
  tasks: TimelineEntry[];
}

export interface StatusReportEntry {
  date: string;
  title: string;
  body: string;
}

export const STATUS_REPORT: StatusReportEntry[] = [
  {
    "date": "2026-04-22",
    "title": "Architecture epic closed — 4 new epics created",
    "body": "DND-2164 closed as Done. All 13 building blocks delivered, NuDS 100%, Expo Go validated, fonts self-hosted, registry aligned. 18 of 22 tasks completed, 1 cancelled, 3 migrated.\n\nFour new epics created for the next phase:\n• DND-2260 — Use Case Content: flow engine + Use Cases across all Product Lines\n• DND-2240 — Flow Management: 4-step Use Case registration wizard\n• DND-2261 — Management UI: Dr Strange integration, source of truth\n• DND-2262 — Screen Compare: visual diff Figma vs live screens"
  },
  {
    "date": "2026-04-22",
    "title": "Building blocks complete, platform stable",
    "body": "Loading, Success and Feedback completed. PIN delivered ahead of schedule. NuDS foundation sprint covered all screens. Nu Sans self-hosted via Vite. HomePage redesigned, responsive breakpoints added."
  },
  {
    "date": "2026-04-16",
    "title": "6 screens shipped — NuDS compliance 100%",
    "body": "Due Date, Down Payment Value/Date, Terms & Conditions, Simulation variants and Eligibility completed. Project Timeline gained editorial report, segmented progress bar, filters and search."
  },
  {
    "date": "2026-04-14",
    "title": "v1.1 — Experience Architecture + Amortization",
    "body": "Experience Architecture replaced Analytics. Use Case Map and Capability Matrix now data-driven. Amortization system (Flat/Price/SAC) with selector in Rules panel."
  },
  {
    "date": "2026-03-28",
    "title": "v1.0 — Platform launch",
    "body": "Web emulator with 5 screens, Glossary, AI Assistant, NuDS theming, i18n (4 locales), password gate. Automated deploy on GitHub Pages."
  }
];

export const EPICS: EpicDefinition[] = [
  {
    "key": "DND-2260",
    "title": "[ Negotiation Flow Platform ] Use Case Content & Flow Navigation",
    "shortTitle": "Use Cases",
    "description": "Flow engine, sequential navigation and activation of Use Cases across all Product Lines as end-to-end flows.",
    "url": "https://nubank.atlassian.net/browse/DND-2260",
    "status": "backlog",
    "tasks": [
      {
        "id": "dnd-2175",
        "jiraKey": "DND-2175",
        "type": "task",
        "title": "[Emulator] Sequential Flow Navigation",
        "status": "backlog",
        "jiraUrl": "https://nubank.atlassian.net/browse/DND-2175",
        "tags": [
          "emulator",
          "expo",
          "navigation"
        ],
        "priority": "high"
      },
      {
        "id": "dnd-2177",
        "jiraKey": "DND-2177",
        "type": "task",
        "title": "[Emulator] Per-Screen Transition Presets",
        "status": "done",
        "date": "2026-04-22",
        "jiraUrl": "https://nubank.atlassian.net/browse/DND-2177",
        "tags": [
          "animation",
          "emulator",
          "expo"
        ],
        "priority": "low"
      },
      {
        "id": "dnd-2190",
        "jiraKey": "DND-2190",
        "type": "task",
        "title": "[Emulator] Use Case Flows — connect screens into end-to-end navigable journeys",
        "status": "backlog",
        "jiraUrl": "https://nubank.atlassian.net/browse/DND-2190",
        "tags": [
          "AppExcellence",
          "Design",
          "design-debt",
          "flow"
        ],
        "priority": "high"
      },
      {
        "id": "dnd-2243",
        "jiraKey": "DND-2243",
        "type": "task",
        "title": "[Use Case] MDR – Multi-debt Renegotiation (dr-mdr-br)",
        "status": "backlog",
        "jiraUrl": "https://nubank.atlassian.net/browse/DND-2243",
        "tags": [
          "debt-resolution",
          "emulator",
          "use-case"
        ],
        "priority": "high"
      },
      {
        "id": "dnd-2244",
        "jiraKey": "DND-2244",
        "type": "task",
        "title": "[Use Case] Late Lending – Short (dr-late-lending-short)",
        "status": "backlog",
        "jiraUrl": "https://nubank.atlassian.net/browse/DND-2244",
        "tags": [
          "debt-resolution",
          "emulator",
          "use-case"
        ],
        "priority": "medium"
      },
      {
        "id": "dnd-2245",
        "jiraKey": "DND-2245",
        "type": "task",
        "title": "[Use Case] Late Lending – Long (dr-late-lending-long)",
        "status": "backlog",
        "jiraUrl": "https://nubank.atlassian.net/browse/DND-2245",
        "tags": [
          "debt-resolution",
          "emulator",
          "use-case"
        ],
        "priority": "medium"
      },
      {
        "id": "dnd-2246",
        "jiraKey": "DND-2246",
        "type": "task",
        "title": "[Use Case] CC Long – Agreements (dr-cc-long-agreements)",
        "status": "backlog",
        "jiraUrl": "https://nubank.atlassian.net/browse/DND-2246",
        "tags": [
          "debt-resolution",
          "emulator",
          "use-case"
        ],
        "priority": "high"
      },
      {
        "id": "dnd-2247",
        "jiraKey": "DND-2247",
        "type": "task",
        "title": "[Use Case] FP – Fatura Parcelada (dr-fp-br)",
        "status": "backlog",
        "jiraUrl": "https://nubank.atlassian.net/browse/DND-2247",
        "tags": [
          "debt-resolution",
          "emulator",
          "use-case"
        ],
        "priority": "medium"
      },
      {
        "id": "dnd-2248",
        "jiraKey": "DND-2248",
        "type": "task",
        "title": "[Use Case] RDP – Renegociação de Pendências (dr-rdp-br)",
        "status": "backlog",
        "jiraUrl": "https://nubank.atlassian.net/browse/DND-2248",
        "tags": [
          "debt-resolution",
          "emulator",
          "use-case"
        ],
        "priority": "medium"
      },
      {
        "id": "dnd-2250",
        "jiraKey": "DND-2250",
        "type": "task",
        "title": "UseCaseRegistryContext — Mutable mock store for Use Cases",
        "status": "backlog",
        "jiraUrl": "https://nubank.atlassian.net/browse/DND-2250",
        "priority": "medium"
      },
      {
        "id": "dnd-2251",
        "jiraKey": "DND-2251",
        "type": "task",
        "title": "[Use Case] Private Payroll (lending-payroll-br)",
        "status": "backlog",
        "jiraUrl": "https://nubank.atlassian.net/browse/DND-2251",
        "tags": [
          "emulator",
          "lending",
          "use-case"
        ],
        "priority": "medium"
      },
      {
        "id": "dnd-2254",
        "jiraKey": "DND-2254",
        "type": "task",
        "title": "FlowManagementPage — Use Case list with management actions",
        "status": "backlog",
        "jiraUrl": "https://nubank.atlassian.net/browse/DND-2254",
        "priority": "medium"
      }
    ]
  },
  {
    "key": "DND-2240",
    "title": "[ Negotiation Flow Platform ] Flow Management — Configure Use Cases Without Touching Code",
    "shortTitle": "UC Wizard",
    "description": "Create and configure Use Cases without touching code. 4-step wizard with TypeScript export and direct launch in the emulator.",
    "url": "https://nubank.atlassian.net/browse/DND-2240",
    "status": "backlog",
    "tasks": [
      {
        "id": "dnd-2258",
        "jiraKey": "DND-2258",
        "type": "task",
        "title": "UseCaseWizardPage — Multi-step Use Case registration wizard (Steps 1–4)",
        "status": "backlog",
        "jiraUrl": "https://nubank.atlassian.net/browse/DND-2258",
        "priority": "medium"
      },
      {
        "id": "dnd-2259",
        "jiraKey": "DND-2259",
        "type": "task",
        "title": "Routes and emulator integration for Flow Management",
        "status": "backlog",
        "jiraUrl": "https://nubank.atlassian.net/browse/DND-2259",
        "priority": "medium"
      }
    ]
  },
  {
    "key": "DND-2261",
    "title": "[ Negotiation Flow Platform ] Flow Management UI",
    "shortTitle": "Dr Strange",
    "description": "Integrate the emulator with the Dr Strange initiative as source of truth. Structured handover, export artifacts, versioning.",
    "url": "https://nubank.atlassian.net/browse/DND-2261",
    "status": "backlog",
    "tasks": [
      {
        "id": "dnd-2180",
        "jiraKey": "DND-2180",
        "type": "task",
        "title": "[ Product Platform ] Prototype – Management User Interface",
        "status": "backlog",
        "jiraUrl": "https://nubank.atlassian.net/browse/DND-2180",
        "priority": "medium"
      },
      {
        "id": "dnd-2263",
        "jiraKey": "DND-2263",
        "type": "task",
        "title": "[ Emulator UI ] Create Report Prototype (NuDS Check) for BDC overview",
        "status": "backlog",
        "jiraUrl": "https://nubank.atlassian.net/browse/DND-2263",
        "priority": "high"
      }
    ]
  },
  {
    "key": "DND-2262",
    "title": "[ Negotiation Flow Platform ] Screen Compare",
    "shortTitle": "Compare",
    "description": "Side-by-side visual comparison between Figma designs and live emulator screens. Diff viewer, overlay mode, AI-assisted analysis.",
    "url": "https://nubank.atlassian.net/browse/DND-2262",
    "status": "backlog",
    "tasks": []
  },
  {
    "key": "DND-2164",
    "title": "[Design the Platform] Negotiation (Hiring) Flow",
    "shortTitle": "Architecture",
    "description": "13 building blocks, NuDS foundation, Expo Go, i18n, web emulator. Closed.",
    "url": "https://nubank.atlassian.net/browse/DND-2164",
    "status": "done",
    "tasks": [
      {
        "id": "rel-1.1",
        "type": "release",
        "title": "v1.1 — Experience Architecture + Amortization",
        "status": "done",
        "date": "2026-04-14",
        "tags": [
          "release"
        ]
      },
      {
        "id": "rel-1.0",
        "type": "release",
        "title": "v1.0 — Platform Launch",
        "status": "done",
        "date": "2026-03-28",
        "tags": [
          "release"
        ]
      },
      {
        "id": "dnd-2166",
        "jiraKey": "DND-2166",
        "type": "task",
        "title": "[Emulator] Due Date Screen",
        "status": "done",
        "date": "2026-04-16",
        "jiraUrl": "https://nubank.atlassian.net/browse/DND-2166",
        "tags": [
          "emulator",
          "expo",
          "flow",
          "screen"
        ],
        "priority": "high"
      },
      {
        "id": "dnd-2167",
        "jiraKey": "DND-2167",
        "type": "task",
        "title": "[Emulator] Down Payment Value Screen",
        "status": "done",
        "date": "2026-04-16",
        "jiraUrl": "https://nubank.atlassian.net/browse/DND-2167",
        "tags": [
          "emulator",
          "expo",
          "flow",
          "screen"
        ],
        "priority": "high"
      },
      {
        "id": "dnd-2168",
        "jiraKey": "DND-2168",
        "type": "task",
        "title": "[Emulator] Down Payment Date Screen",
        "status": "done",
        "date": "2026-04-16",
        "jiraUrl": "https://nubank.atlassian.net/browse/DND-2168",
        "tags": [
          "emulator",
          "expo",
          "flow",
          "screen"
        ],
        "priority": "medium"
      },
      {
        "id": "dnd-2169",
        "jiraKey": "DND-2169",
        "type": "task",
        "title": "[Emulator] Terms & Conditions Screen",
        "status": "done",
        "date": "2026-04-16",
        "jiraUrl": "https://nubank.atlassian.net/browse/DND-2169",
        "tags": [
          "emulator",
          "expo",
          "screen"
        ],
        "priority": "high"
      },
      {
        "id": "dnd-2170",
        "jiraKey": "DND-2170",
        "type": "task",
        "title": "[Emulator] PIN Screen",
        "status": "done",
        "date": "2026-04-20",
        "jiraUrl": "https://nubank.atlassian.net/browse/DND-2170",
        "tags": [
          "emulator",
          "expo",
          "screen"
        ],
        "priority": "medium"
      },
      {
        "id": "dnd-2171",
        "jiraKey": "DND-2171",
        "type": "task",
        "title": "[Emulator] Loading Screen",
        "status": "done",
        "date": "2026-04-20",
        "jiraUrl": "https://nubank.atlassian.net/browse/DND-2171",
        "tags": [
          "emulator",
          "expo",
          "screen"
        ],
        "priority": "medium"
      },
      {
        "id": "dnd-2172",
        "jiraKey": "DND-2172",
        "type": "task",
        "title": "[Emulator] Success Screen",
        "status": "done",
        "date": "2026-04-20",
        "jiraUrl": "https://nubank.atlassian.net/browse/DND-2172",
        "tags": [
          "emulator",
          "expo",
          "screen"
        ],
        "priority": "medium"
      },
      {
        "id": "dnd-2173",
        "jiraKey": "DND-2173",
        "type": "task",
        "title": "[Emulator] Feedback Screen",
        "status": "done",
        "date": "2026-04-20",
        "jiraUrl": "https://nubank.atlassian.net/browse/DND-2173",
        "tags": [
          "emulator",
          "expo",
          "screen"
        ],
        "priority": "medium"
      },
      {
        "id": "dnd-2174",
        "jiraKey": "DND-2174",
        "type": "task",
        "title": "[Emulator] App.tsx Routing Integration",
        "status": "done",
        "date": "2026-04-22",
        "jiraUrl": "https://nubank.atlassian.net/browse/DND-2174",
        "tags": [
          "emulator",
          "expo",
          "routing"
        ],
        "priority": "high"
      },
      {
        "id": "dnd-2176",
        "jiraKey": "DND-2176",
        "type": "task",
        "title": "[Emulator] Registry & Config Updates",
        "status": "done",
        "date": "2026-04-22",
        "jiraUrl": "https://nubank.atlassian.net/browse/DND-2176",
        "tags": [
          "config",
          "documentation",
          "emulator"
        ],
        "priority": "medium"
      },
      {
        "id": "dnd-2178",
        "jiraKey": "DND-2178",
        "type": "task",
        "title": "[ Glossary ] Mock content in Expo Go app",
        "status": "done",
        "date": "2026-04-22",
        "jiraUrl": "https://nubank.atlassian.net/browse/DND-2178",
        "priority": "low"
      },
      {
        "id": "dnd-2179",
        "jiraKey": "DND-2179",
        "type": "task",
        "title": "[ Experience Architecture ] Design and Mock New Session",
        "status": "cancelled",
        "jiraUrl": "https://nubank.atlassian.net/browse/DND-2179",
        "priority": "medium"
      },
      {
        "id": "dnd-2181",
        "jiraKey": "DND-2181",
        "type": "task",
        "title": "[ Figma Design ] Check Design NuDS Hiring Flow Screen ",
        "status": "done",
        "date": "2026-04-15",
        "jiraUrl": "https://nubank.atlassian.net/browse/DND-2181",
        "priority": "medium"
      },
      {
        "id": "dnd-2182",
        "jiraKey": "DND-2182",
        "type": "task",
        "title": "[ Design & Emulator ] Simulation Screen + new variants",
        "status": "done",
        "date": "2026-04-16",
        "jiraUrl": "https://nubank.atlassian.net/browse/DND-2182",
        "tags": [
          "flow"
        ],
        "priority": "medium"
      },
      {
        "id": "dnd-2187",
        "jiraKey": "DND-2187",
        "type": "task",
        "title": "[Platform] Experience Architecture — Use Case Map + Capability Matrix",
        "status": "done",
        "date": "2026-04-14",
        "jiraUrl": "https://nubank.atlassian.net/browse/DND-2187",
        "priority": "high"
      },
      {
        "id": "dnd-2188",
        "jiraKey": "DND-2188",
        "type": "task",
        "title": "[Emulator] Amortization Tables — Flat/Price/SAC formula selector + Use Case driven rules",
        "status": "done",
        "date": "2026-04-14",
        "jiraUrl": "https://nubank.atlassian.net/browse/DND-2188",
        "priority": "high"
      },
      {
        "id": "dnd-2189",
        "jiraKey": "DND-2189",
        "type": "task",
        "title": "[Emulator] Financial Rules Panel — consolidated configuration drawer",
        "status": "done",
        "date": "2026-04-14",
        "jiraUrl": "https://nubank.atlassian.net/browse/DND-2189",
        "priority": "medium"
      },
      {
        "id": "dnd-2191",
        "jiraKey": "DND-2191",
        "type": "task",
        "title": "[Platform] Expo Go Equalization — simplified mobile companion",
        "status": "done",
        "date": "2026-04-22",
        "jiraUrl": "https://nubank.atlassian.net/browse/DND-2191",
        "priority": "medium"
      },
      {
        "id": "dnd-2207",
        "jiraKey": "DND-2207",
        "type": "task",
        "title": "[Emulator] Eligibility Screen",
        "status": "done",
        "date": "2026-04-16",
        "jiraUrl": "https://nubank.atlassian.net/browse/DND-2207",
        "tags": [
          "emulator",
          "expo",
          "screen"
        ],
        "priority": "high"
      }
    ]
  }
];

export const TIMELINE: TimelineEntry[] = EPICS.flatMap((e) => e.tasks);

export const EPIC = {
  key: EPICS[0].key,
  title: EPICS[0].title,
  url: EPICS[0].url,
  status: EPICS[0].status,
};
