export interface GlossaryEntry {
  acronym: string;
  definition: string;
  explanation: string;
}

export const GLOSSARY_DATA: GlossaryEntry[] = [
  {
    acronym: 'AABI',
    definition: 'Anticipation Adjusted Booked Interest',
    explanation: 'Financial metric used to calculate interest revenue accounting for early payments made before the due date.',
  },
  {
    acronym: 'ARPAC',
    definition: 'Average Revenue Per Active Customer',
    explanation: 'Metric indicating the average revenue generated by each actively engaged customer within a given period.',
  },
  {
    acronym: 'AuC',
    definition: 'Assets Under Custody',
    explanation: 'Total value of financial assets (stocks, bonds, etc.) held and administered by an institution on behalf of its clients.',
  },
  {
    acronym: 'AUM',
    definition: 'Assets Under Management',
    explanation: 'Total market value of all investments a financial institution manages on behalf of its clients.',
  },
  {
    acronym: 'BDC',
    definition: 'Backend Driven Content',
    explanation: 'Development technique where the server decides what appears on the app screen, allowing UI changes without an app store update.',
  },
  {
    acronym: 'BHAG',
    definition: 'Big Hairy Audacious Goal',
    explanation: 'An extremely ambitious long-term strategic objective used to inspire and focus the entire organization.',
  },
  {
    acronym: 'CAGR',
    definition: 'Compounded Annual Growth Rate',
    explanation: 'Rate showing the average annual growth of an investment or metric over a specific period, assuming reinvestment.',
  },
  {
    acronym: 'CC',
    definition: 'Credit Card',
    explanation: 'Payment method with a pre-approved credit limit for installment purchases.',
  },
  {
    acronym: 'CDB',
    definition: 'Bank Deposit Certificate',
    explanation: 'Fixed-income security issued by banks in Brazil to raise funds, paying interest to the investor.',
  },
  {
    acronym: 'CICO',
    definition: 'Cash In / Cash Out',
    explanation: 'Term describing deposit (cash in) and withdrawal/transfer (cash out) operations in an account or wallet.',
  },
  {
    acronym: 'CNBV',
    definition: 'National Banking and Securities Commission',
    explanation: 'Financial regulatory body of Mexico, equivalent to a combined Central Bank and Securities Commission.',
  },
  {
    acronym: 'DA',
    definition: 'Destination Architecture',
    explanation: 'In IT projects, the ideal or final technical structure planned after a migration or transformation.',
  },
  {
    acronym: 'EOY',
    definition: 'End of Year',
    explanation: 'Refers to goals, closings, or metrics accumulated through the end of the fiscal or calendar year.',
  },
  {
    acronym: 'FGI',
    definition: 'Brazilian Government Credit Fund',
    explanation: 'BNDES fund serving as a guarantee to facilitate credit access for businesses.',
  },
  {
    acronym: 'FT-based',
    definition: 'Foundational Test Based',
    explanation: 'Decisions or developments guided by foundational structural tests to validate stability before moving forward.',
  },
  {
    acronym: 'FXN',
    definition: 'FX Neutral',
    explanation: 'Metric adjusted to remove the impact of exchange rate fluctuations, enabling evaluation of real business growth.',
  },
  {
    acronym: 'LND',
    definition: 'Lending',
    explanation: 'Business area focused on granting loans to customers, generating revenue through interest.',
  },
  {
    acronym: 'LTV',
    definition: 'Lifetime Value',
    explanation: 'Estimate of how much profit a customer generates for the company during the entire period they remain a customer.',
  },
  {
    acronym: 'MB',
    definition: 'Money Box',
    explanation: 'Feature (common in digital banks) for separating and saving money toward specific goals.',
  },
  {
    acronym: 'MM',
    definition: 'Mass Market',
    explanation: 'Consumer segment encompassing the majority of the population; standardized products designed for high volume.',
  },
  {
    acronym: 'MVP',
    definition: 'Minimum Viable Product',
    explanation: 'The simplest version of a product launched to test whether the idea works in the market with minimal effort.',
  },
  {
    acronym: 'NPL',
    definition: 'Non-Performing Loan',
    explanation: 'Loans overdue for a certain period (typically 90+ days) with a high risk of not being repaid.',
  },
  {
    acronym: 'NPS',
    definition: 'Net Promoter Score',
    explanation: 'Loyalty and satisfaction metric measuring the likelihood of a customer recommending the company or product.',
  },
  {
    acronym: 'NPV',
    definition: 'Net Present Value',
    explanation: 'Financial calculation determining the current worth of an investment that will yield future returns, discounted at a given rate.',
  },
  {
    acronym: 'PnL',
    definition: 'Profit and Loss',
    explanation: 'Report summarizing revenues, costs, and expenses to show whether the company made a profit or loss in the period.',
  },
  {
    acronym: 'RSCA',
    definition: 'Risk and Control Self-Assessment',
    explanation: 'Process where internal teams identify their operational risks and evaluate whether their controls are effective.',
  },
  {
    acronym: 'SPEI',
    definition: 'Electronic Payment System (Mexico)',
    explanation: 'Mexico\'s real-time bank transfer system, similar to PIX or wire transfers in other countries.',
  },
  {
    acronym: 'TTFD',
    definition: 'Time to Full Display',
    explanation: 'Technical metric measuring how long it takes for a screen or page to fully render all visible content to the user.',
  },
  {
    acronym: 'VoC',
    definition: 'Voice of Customer',
    explanation: 'Process of collecting and analyzing customer feedback to understand their needs and improve products.',
  },
  {
    acronym: 'WER',
    definition: 'Weekly Engagement Rate',
    explanation: 'Percentage of users who actively interact with the product within a given week.',
  },
  {
    acronym: 'YoY',
    definition: 'Year over Year',
    explanation: 'Method of comparing financial results or metrics from this year with the same period last year to assess growth.',
  },
];
